### ISSUE TITLE
Rename branch name from `master` to `main`

### ISSUE THREAD

**Issue by mgrider** [daveverwer/iOSDevDirectory#703]
This should be relatively easy, but will probably be complicated by whatever CI you're using (looks like Travis). Looks like you might be able to just add:

```yml
branches:
  only:
    - main
```

...to `.travis.yml` after you rename it.
